export const en = {
  home: {
    heroScript: 'Authentic',
    categoriesTitle: 'What are you craving?',
    aboutHeading1: 'Born in Verón.',
    aboutHeading2: 'Built to Last.',
    aboutCta: 'Our Story',
    features: [
      { title: 'Handcrafted', desc: 'Every pizza made to order.' },
      { title: 'Fresh Seafood', desc: 'Caribbean-sourced mariscos.' },
      { title: 'Live Nights', desc: 'DJs every weekend.' },
    ],
    picksLabel: 'Our Picks',
    picksTitle: 'Fan Favorites',
    banner1Label: 'Signature Pizza',
    banner1Cta: 'Order Now',
    bestSeller: 'Best Seller',
    banner2Label: 'Every Weekend',
    banner2Title: 'Live DJ Night',
    banner2Cta: 'See Events',
    friSat: 'Fri & Sat',
    night: 'Night',
    storyPin: [
      { title: 'Artisan Dough', body: 'Made fresh daily — fermented 48 hours for a crust that bites back.' },
      { title: 'Premium Toppings', body: 'Local mariscos, imported cheeses, hand-crushed tomato. Nothing comes from a can.' },
      { title: 'Caribbean Soul', body: "Born in Verón. Every slice carries the energy of Punta Cana's boldest neighborhood." },
    ],
    heroOrderTitle: 'Order',
    heroOrderSub: 'Your Pizza',
    todaysSpecialLine1: "Today's",
    todaysSpecialLine2: 'Special',
    ctaBannerSlogan: 'Unmatched Dining Experience · Verón, Punta Cana',
    exclusiveLabel: 'Exclusive',
    exclusiveTitle: 'Our Menu',
    fullMenu: 'Full Menu',
    whyLabel: "Why D'Pavo",
    whyTitle: 'The Difference',
    whyItems: [
      { title: 'Artisan Pizzas',        desc: 'Made fresh daily with premium imported and local ingredients.' },
      { title: 'Fresh Mariscos',        desc: 'Caribbean seafood sourced daily — shrimp, calamari and more.' },
      { title: 'Nightlife Energy',      desc: 'DJs every weekend and themed events that keep Verón moving.' },
      { title: 'Prime Location',        desc: "Located in Verón, the heart of Punta Cana's local culture." },
      { title: 'Fast WhatsApp Orders',  desc: 'Order directly on WhatsApp. No apps, no waiting. Instant service.' },
      { title: 'Community Roots',       desc: "Born and built in Verón. We're proud of where we came from." },
    ],
  },
  nav: {
    home: 'Home',
    menu: 'Menu',
    events: 'Events',
    about: 'About',
    gallery: 'Gallery',
    contact: 'Contact',
    order: 'Order',
    lang: 'ES',
  },
  hero: {
    kicker: "Verón's #1 Urban Pizzeria",
    title1: 'Eat.',
    title2: 'Drink.',
    title3: 'Party.',
    subtitle: 'Handcrafted pizzas, fresh seafood and a nightlife energy that hits different in Punta Cana.',
    cta1: 'View Menu',
    cta2: 'Tonight',
    hours: '11:00 AM – Late Night',
    location: 'Plaza Verón Center',
  },
  marquee: [
    'Eat · Drink · Party',
    'Urban Tropical Energy',
    'Verón, Punta Cana',
    'Pizza · Mariscos · Drinks',
  ],
  signature: {
    label: 'Signature Selection',
    title: 'Built to sell the craving.',
    subtitle: 'Our most-ordered plates — handcrafted, bold and made to be talked about.',
    order: 'Order on WhatsApp',
    trending: 'Trending',
  },
  howItWorks: {
    label: 'How It Works',
    title: 'Order in 3 steps.',
    steps: [
      { title: 'Choose Your Order', copy: 'Browse our menu and pick your favorites — pizza, mariscos, picaderas or drinks.' },
      { title: 'Message Us on WhatsApp', copy: 'Send us your order directly on WhatsApp. No apps, no wait time, no hassle.' },
      { title: 'Sit Back & Enjoy', copy: "We'll take care of the rest. Your food arrives fresh, fast and full of flavor." },
    ],
  },
  dayNight: {
    day: {
      label: 'Day Vibes',
      title: 'Family. Flavors. Sunshine.',
      copy: 'Afternoons at D\'Pavo are made for good food and easy conversation. Bring the family, bring your appetite.',
    },
    night: {
      label: 'Night Mode',
      title: 'Beats. Bottles. Bass.',
      copy: "When the sun goes down, D'Pavo transforms. DJs, live events and premium drinks — the best night in Verón starts here.",
    },
  },
  reviews: {
    label: 'What People Say',
    title: 'Real love from real guests.',
  },
  hours: {
    label: 'Find Us',
    title: 'Opening Hours.',
    address: 'HHXG+J29, 106, Punta Cana 23000',
    schedule: [
      { day: 'Monday – Thursday', hours: '11:00 AM – 11:00 PM' },
      { day: 'Friday', hours: '11:00 AM – 2:00 AM' },
      { day: 'Saturday', hours: '11:00 AM – 3:00 AM' },
      { day: 'Sunday', hours: '12:00 PM – 10:00 PM' },
    ],
    cta: 'Get Directions on WhatsApp',
  },
  eventsCta: {
    label: 'Nightlife Calendar',
    title: 'Programming that feels alive.',
    link: 'Open Events Page',
  },
  cta: {
    label: "Don't Miss Out",
    title: 'The party never stops.',
    subtitle: "From lunch to last call, D'Pavo is where Verón comes alive. Pick up the phone and join the energy.",
    cta1: 'View Menu',
    cta2: 'Reserve on WhatsApp',
  },
  footer: {
    tagline: "Verón's urban pizzeria — where flavor meets nightlife.",
    explore: 'Explore',
    visit: 'Visit',
    address: 'HHXG+J29, 106, Punta Cana 23000',
    hoursShort: '11:00 AM — Late Night',
    whatsapp: 'WhatsApp Reservations',
    rights: "D'Pavo Urban Pizzeria.",
    findUs: 'Find Us',
    openingHours: 'Opening Hours',
    connect: 'Connect',
    schedule: [
      { day: 'Mon – Thu', hours: '11 AM – 12 AM' },
      { day: 'Fri – Sat', hours: '11 AM – 2 AM'  },
      { day: 'Sunday',    hours: '11 AM – 12 AM' },
    ],
  },
  menuPage: {
    label: 'High-Octane Flavors',
    title: 'The Menu.',
    subtitle: 'Bold, fresh and built for cravings. Every item on this menu earns its spot.',
    categories: ['All', 'Pizza', 'Mariscos', 'Picaderas', 'Drinks'],
    featured: 'Featured',
    trending: 'Trending',
    order: 'Order on WhatsApp',
    ask: 'Ask on WhatsApp',
  },
  eventsPage: {
    label: 'Nightlife & Events',
    title: 'Events & Nightlife.',
    subtitle: "Every week brings something new. From karaoke nights to DJ sets — D'Pavo is always moving.",
    featuredLabel: 'Main Event',
    reserve: 'Reserve Table',
    vibeLabel: 'The Vibe',
    vibeTitle: 'More than a restaurant.',
    vibes: [
      { title: 'Weekly Programming', copy: 'Something different every night of the week — karaoke, DJ sets, themed nights and more.' },
      { title: 'VIP Energy', copy: 'Bottle service, premium reservations and the best table in the house. Ask us about VIP.' },
      { title: 'Live DJ Sets', copy: 'Local and regional DJs bringing the best urban, tropical and Latin sounds to Verón.' },
    ],
    notifyLabel: 'Stay in the Loop',
    notifyTitle: 'Get notified about upcoming events.',
    notifyCta: 'Join on WhatsApp',
    weeklyLabel: 'Weekly Programming',
    weeklyTitle: 'Urban Calendar.',
    reserveNow: 'Reserve Now',
  },
  aboutPage: {
    label: 'Our Story',
    title: 'Our Story.',
    venuePlaceholder: 'Venue Photo',
    subtitle: "Born in Verón, built for everyone — D'Pavo is the intersection of flavor, culture and urban energy.",
    storyTitle: "How D'Pavo Started.",
    storyBody: [
      "D'Pavo was born from a simple idea: Verón deserved a spot where great food and great energy lived under the same roof. We started with a vision of handcrafted pizzas, fresh Dominican seafood and a nightlife vibe that felt genuinely local.",
      "What started as a neighborhood pizzeria quickly grew into something more — a gathering place, a weekly ritual, a destination. Word spread fast. The food spoke for itself. The energy did the rest.",
      "Today, D'Pavo is more than a restaurant. It's where Verón comes to eat, drink and celebrate. We're proud of where we started and excited about where we're going.",
    ],
    valuesLabel: 'What We Stand For',
    valuesTitle: 'Built on Three Pillars.',
    values: [
      { title: 'Quality First', copy: 'Every ingredient is chosen with intention. Every plate leaves the kitchen with pride.' },
      { title: 'Local Roots', copy: "We're a Verón original. Everything we do is rooted in the community that built us." },
      { title: 'Unforgettable Nights', copy: 'Food is just the beginning. The experience — the energy, the music, the people — is what makes D\'Pavo different.' },
    ],
    teamLabel: 'The Team',
    teamTitle: "The people behind D'Pavo.",
    visitLabel: 'Come See Us',
    visitTitle: "We're Always Open.",
    visitCta: 'Get Directions',
  },
  galleryPage: {
    label: 'Gallery',
    title: 'The Vibe.',
    subtitle: "Food, nights and the energy of D'Pavo — captured.",
    categories: ['All', 'Food', 'Venue', 'Events'],
  },
  cookieConsent: {
    text: 'We use cookies to improve your experience and analyze site traffic.',
    learnMore: 'Learn more',
    decline: 'Decline',
    accept: 'Accept',
  },
  notFound: {
    title: 'Page Not Found',
    body: 'Looks like this slice got lost. Head back and find something better on the menu.',
    cta: 'Back to Home',
  },
  contactPage: {
    label: 'Visit Us',
    title: 'Find Us.',
    subtitle: "Come for the pizza, stay for the energy. We're waiting for you in Verón, Punta Cana.",
    addressLabel: 'Address',
    address: 'Plaza Verón Center, Verón, Punta Cana 23000',
    phoneLabel: 'Phone',
    phone: '(829) 753-1995',
    hoursLabel: 'Opening Hours',
    schedule: [
      { day: 'Monday – Thursday', hours: '11:00 AM – 11:00 PM' },
      { day: 'Friday', hours: '11:00 AM – 2:00 AM' },
      { day: 'Saturday', hours: '11:00 AM – 3:00 AM' },
      { day: 'Sunday', hours: '12:00 PM – 10:00 PM' },
    ],
    waCta: 'Start Your Order',
    ctaTitle: 'Ready to order?',
    ctaSubtitle: 'Skip the wait — send us your order directly on WhatsApp and we\'ll have it ready.',
    mapLabel: 'Get Directions',
    socialLabel: 'Follow Us',
  },
};

export type Content = typeof en;
