// src/content/es.ts
import type { Content } from './en';

export const es: Content = {
  home: {
    heroScript: 'Auténtico',
    categoriesTitle: '¿Qué se te antoja?',
    aboutHeading1: 'Nacido en Verón.',
    aboutHeading2: 'Para Quedarse.',
    aboutCta: 'Nuestra Historia',
    features: [
      { title: 'Artesanal', desc: 'Cada pizza hecha al momento.' },
      { title: 'Mariscos Frescos', desc: 'Mariscos del Caribe.' },
      { title: 'Noches en Vivo', desc: 'DJs cada fin de semana.' },
    ],
    picksLabel: 'Nuestros Picks',
    picksTitle: 'Los Favoritos',
    banner1Label: 'Pizza Estrella',
    banner1Cta: 'Ordenar Ahora',
    bestSeller: 'El Más Pedido',
    banner2Label: 'Cada Fin de Semana',
    banner2Title: 'Noche de DJ',
    banner2Cta: 'Ver Eventos',
    friSat: 'Vie & Sáb',
    night: 'Noche',
    storyPin: [
      { title: 'Masa Artesanal', body: 'Hecha diariamente — fermentada 48 horas para una corteza que lo dice todo.' },
      { title: 'Ingredientes Premium', body: 'Mariscos locales, quesos importados, tomate triturado a mano. Nada viene de lata.' },
      { title: 'Alma Caribeña', body: 'Nacido en Verón. Cada rebanada lleva la energía del barrio más auténtico de Punta Cana.' },
    ],
    heroOrderTitle: 'Ordena',
    heroOrderSub: 'Tu Pizza',
    todaysSpecialLine1: 'Especial',
    todaysSpecialLine2: 'del Día',
    ctaBannerSlogan: 'Experiencia Gastronómica Inigualable · Verón, Punta Cana',
    exclusiveLabel: 'Exclusivo',
    exclusiveTitle: 'Nuestro Menú',
    fullMenu: 'Menú Completo',
    whyLabel: "Por Qué D'Pavo",
    whyTitle: 'La Diferencia',
    whyItems: [
      { title: 'Pizzas Artesanales',          desc: 'Elaboradas diariamente con ingredientes premium locales e importados.' },
      { title: 'Mariscos Frescos',            desc: 'Mariscos del Caribe traídos cada día — camarones, calamares y más.' },
      { title: 'Energía Nocturna',            desc: 'DJs cada fin de semana y eventos temáticos que mantienen a Verón en movimiento.' },
      { title: 'Ubicación Privilegiada',      desc: 'En el corazón de Verón, el núcleo cultural de Punta Cana.' },
      { title: 'Pedidos Rápidos por WhatsApp', desc: 'Ordena directo por WhatsApp. Sin apps, sin esperas. Servicio inmediato.' },
      { title: 'Raíces Comunitarias',         desc: 'Nacidos y construidos en Verón. Orgullosos de nuestros orígenes.' },
    ],
  },
  nav: {
    home: 'Inicio',
    menu: 'Menú',
    events: 'Noche',
    about: 'Nuestra Historia',
    gallery: 'Galería',
    contact: 'Contacto',
    catering: 'Catering',
    order: 'Ordena',
    lang: 'EN',
  },
  hero: {
    kicker: 'En vivo desde Verón, Punta Cana',
    title1: 'Come.',
    title2: 'Bebe.',
    title3: 'Fiesta.',
    subtitle: 'Sabores tropicales urbanos de día. Energía nocturna de noche. Una sola dirección en Verón.',
    cta1: 'Ver Menú',
    cta2: 'Esta Noche',
    hours: '11:00 AM – Madrugada',
    location: 'Plaza Verón Center',
  },
  marquee: [
    'Come · Bebe · Fiesta',
    'Energía Tropical Urbana',
    'Verón, Punta Cana',
    'Pizza · Mariscos · Drinks',
  ],
  signature: {
    label: 'Selección Especial',
    title: 'Creado para despertar el antojo.',
    subtitle: 'Nuestros platos más pedidos — ingredientes premium, sabores intensos.',
    order: 'Pedir por WhatsApp',
    trending: 'Tendencia',
  },
  howItWorks: {
    label: 'Cómo Funciona',
    title: 'Ordena en 3 pasos.',
    steps: [
      { title: 'Elige tu Pedido', copy: 'Explora el menú y selecciona lo que quieres.' },
      { title: 'Escríbenos por WhatsApp', copy: 'Toca el botón y envía tu pedido directamente.' },
      { title: 'Relájate y Disfruta', copy: 'Lo preparamos fresco. Recoge o disfruta en el local.' },
    ],
  },
  dayNight: {
    day: {
      label: 'El Día',
      title: 'Familia. Sabores. Sol.',
      copy: 'Energía vibrante al mediodía, ambiente cálido y la mejor pizza de Verón.',
    },
    night: {
      label: 'La Noche',
      title: 'Beats. Botellas. Bajo.',
      copy: "DJs, noches de karaoke y ambiente inmersivo — D'Pavo es más que un restaurante.",
    },
  },
  reviews: {
    label: 'Lo Que Dicen',
    title: 'Amor real de clientes reales.',
  },
  hours: {
    label: 'Visítanos',
    title: 'Horario de Apertura.',
    address: 'HHXG+J29, 106, Punta Cana 23000',
    schedule: [
      { day: 'Lunes – Jueves', hours: '11:00 AM – 11:00 PM' },
      { day: 'Viernes', hours: '11:00 AM – 2:00 AM' },
      { day: 'Sábado', hours: '11:00 AM – 3:00 AM' },
      { day: 'Domingo', hours: '12:00 PM – 10:00 PM' },
    ],
    cta: 'Cómo Llegar por WhatsApp',
  },
  eventsCta: {
    label: 'Calendario Nocturno',
    title: 'Programación que se siente viva.',
    link: 'Ver Eventos',
  },
  cta: {
    label: 'No te Pierdas Nada',
    title: 'La fiesta nunca para.',
    subtitle: 'Ordena ahora, reserva una mesa o simplemente ven — siempre estamos encendidos.',
    cta1: 'Ver Menú',
    cta2: 'Reservar por WhatsApp',
  },
  footer: {
    tagline: 'Pizza, tragos y vida nocturna en Verón. Más fuerte, más intenso, más memorable.',
    explore: 'Explorar',
    visit: 'Visítanos',
    address: 'HHXG+J29, 106, Punta Cana 23000',
    hoursShort: '11:00 AM — Madrugada',
    whatsapp: 'Reservas por WhatsApp',
    rights: "D'Pavo Urban Pizzeria.",
    findUs: 'Encuéntranos',
    openingHours: 'Horario de Apertura',
    connect: 'Contáctanos',
    schedule: [
      { day: 'Lun – Jue', hours: '11 AM – 12 AM' },
      { day: 'Vie – Sáb', hours: '11 AM – 2 AM'  },
      { day: 'Domingo',   hours: '11 AM – 12 AM' },
    ],
  },
  menuPage: {
    label: 'Sabores de Alto Octanaje',
    title: 'El Menú.',
    subtitle: 'Pizzas, mariscos, picaderas y bebidas — todo disponible por WhatsApp.',
    categories: ['Todo', 'Pizza', 'Mariscos', 'Picaderas', 'Bebidas'],
    featured: 'Destacado',
    trending: 'Tendencia',
    order: 'Pedir por WhatsApp',
    ask: 'Consultar por WhatsApp',
    searchPlaceholder: 'Buscar plato, ingrediente…',
  },
  eventsPage: {
    label: '¿Qué pasa esta noche?',
    title: 'Eventos y Vida Nocturna.',
    subtitle: 'DJs, karaoke y locura total cada semana en Verón.',
    featuredLabel: 'Evento Principal',
    reserve: 'Reservar Mesa',
    vibeLabel: 'El Ambiente',
    vibeTitle: 'Más que un restaurante.',
    vibes: [
      { title: 'Sets de DJ', copy: 'House, reggaetón y mezclas urbanas todos los viernes y sábados.' },
      { title: 'Música en Vivo', copy: 'Artistas locales y sorpresas a lo largo del mes.' },
      { title: 'Noches de Karaoke', copy: 'Todos los jueves — el público toma el micrófono.' },
    ],
    notifyLabel: 'Mantente Informado',
    notifyTitle: 'Recibe notificaciones de próximos eventos.',
    notifyCta: 'Únete por WhatsApp',
    weeklyLabel: 'Programación Semanal',
    weeklyTitle: 'Calendario Urbano.',
    reserveNow: 'Reservar Ahora',
  },
  aboutPage: {
    label: 'Nuestra Historia',
    title: 'Nuestra Historia.',
    venuePlaceholder: 'Foto del Local',
    subtitle: 'Un lugar nacido en Verón con ambición, sabor y ritmo.',
    storyTitle: "Cómo Empezó D'Pavo.",
    storyBody: [
      "D'Pavo nació de una idea simple: llevar pizza premium y de sabores intensos al corazón de Verón, Punta Cana — un barrio lleno de energía, cultura y gente hambrienta.",
      'Lo que comenzó como una pequeña operación de cocina rápidamente se convirtió en un destino urbano completo. La comida mejoró, las noches se pusieron más intensas y la marca tomó vida propia.',
      "Hoy D'Pavo es donde los locales comen, los turistas descubren y la vida nocturna comienza.",
    ],
    valuesLabel: 'En Qué Creemos',
    valuesTitle: 'Construido Sobre Tres Pilares.',
    values: [
      { title: 'Raíces Locales', copy: 'Nacidos y criados en Verón. Compramos local, pensamos local y devolvemos localmente.' },
      { title: 'Energía Urbana', copy: "De día o de noche, D'Pavo trae la energía — comida, música y ambiente." },
      { title: 'Ingredientes Premium', copy: 'Cada pizza, cada trago, cada plato está hecho con calidad que se nota.' },
    ],
    teamLabel: 'El Equipo',
    teamTitle: 'Las personas detrás de D\'Pavo.',
    visitLabel: 'Ven a Vernos',
    visitTitle: 'Siempre Abiertos.',
    visitCta: 'Cómo Llegar',
  },
  galleryPage: {
    label: 'Galería',
    title: 'El Ambiente.',
    subtitle: "Comida, noches y la energía de D'Pavo — capturada.",
    categories: ['Todo', 'Comida', 'Local', 'Eventos'],
  },
  cateringPage: {
    label: 'Eventos Privados',
    title: 'Catering.',
    subtitle: "Lleva D'Pavo a tu evento. Pizza artesanal, mariscos frescos y servicio completo — donde celebres.",
    introTitle: "Tu Evento. Nuestros Sabores.",
    introBody: "Ya sea un cumpleaños, reunión corporativa, boda o cualquier ocasión privada, D'Pavo lleva los mismos sabores y la energía que nos definen en Verón — directo a tu lugar.",
    servicesLabel: 'Qué Ofrecemos',
    servicesTitle: 'Catering Completo.',
    services: [
      { title: 'Menú Personalizado', desc: 'Diseñamos el menú según tus invitados — pizzas al horno, mariscos frescos y bebidas especiales.' },
      { title: 'Instalación Completa', desc: 'Llegamos temprano, montamos todo y recogemos al final. Tú disfrutas, nosotros nos encargamos.' },
      { title: 'Personal Profesional', desc: 'Meseros y cocineros capacitados que representan los estándares de D\'Pavo en tu evento.' },
      { title: 'En el Lugar o Entrega', desc: 'Cocinamos in situ o entregamos pedidos listos — lo que mejor se adapte a tu evento.' },
    ],
    stepsLabel: 'Cómo Funciona',
    stepsTitle: 'Proceso Simple.',
    steps: [
      { num: '01', title: 'Contáctanos', desc: 'Envíanos un WhatsApp con la fecha, tamaño y visión de tu evento.' },
      { num: '02', title: 'Planificamos Juntos', desc: 'Adaptamos el menú y el servicio a lo que necesita tu evento.' },
      { num: '03', title: 'Disfruta', desc: 'Tus invitados comen bien, tú quedas perfecto. D\'Pavo se encarga de todo.' },
    ],
    ctaLabel: 'Solicitar Cotización',
    ctaTitle: '¿Listo para Planificar tu Evento?',
    ctaBody: 'Hagámoslo inolvidable. Escríbenos y te respondemos en pocas horas.',
    ctaBtn: 'Escríbenos por WhatsApp',
  },
  cookieConsent: {
    text: 'Usamos cookies para mejorar tu experiencia y analizar el tráfico del sitio.',
    learnMore: 'Más info',
    decline: 'Rechazar',
    accept: 'Aceptar',
  },
  notFound: {
    title: 'Página No Encontrada',
    body: 'Parece que esta rebanada se perdió. Regresa y encuentra algo mejor en el menú.',
    cta: 'Volver al Inicio',
  },
  contactPage: {
    label: 'Visítanos',
    title: 'Encuéntranos.',
    subtitle: 'Ven por la pizza, quédate por la energía. Te esperamos en Verón, Punta Cana.',
    addressLabel: 'Dirección',
    address: 'Plaza Verón Center, Verón, Punta Cana 23000',
    phoneLabel: 'Teléfono',
    phone: '(829) 753-1995',
    hoursLabel: 'Horario de Atención',
    schedule: [
      { day: 'Lunes – Jueves', hours: '11:00 AM – 11:00 PM' },
      { day: 'Viernes', hours: '11:00 AM – 2:00 AM' },
      { day: 'Sábado', hours: '11:00 AM – 3:00 AM' },
      { day: 'Domingo', hours: '12:00 PM – 10:00 PM' },
    ],
    waCta: 'Hacer tu Pedido',
    ctaTitle: '¿Listo para ordenar?',
    ctaSubtitle: 'Sin esperas — envíanos tu pedido por WhatsApp y lo tendremos listo.',
    mapLabel: 'Cómo Llegar',
    socialLabel: 'Síguenos',
  },
};
