// src/content/es.ts
import type { Content } from './en';

export const es: Content = {
  home: {
    heroScript: 'Auténtico',
    categoriesTitle: '¿Qué se te antoja?',
    aboutHeading1: 'Nacido en Verón.',
    aboutHeading2: 'Para Quedarse.',
    aboutCta: 'Nuestra Historia',
    features: [
      { title: 'Artesanal', desc: 'Cada pizza hecha al momento.' },
      { title: 'Mariscos Frescos', desc: 'Mariscos del Caribe.' },
      { title: 'Noches en Vivo', desc: 'DJs cada fin de semana.' },
    ],
    picksLabel: 'Nuestros Picks',
    picksTitle: 'Los Favoritos',
    banner1Label: 'Pizza Estrella',
    banner1Cta: 'Ordenar Ahora',
    bestSeller: 'El Más Pedido',
    banner2Label: 'Cada Fin de Semana',
    banner2Title: 'Noche de DJ',
    banner2Cta: 'Ver Eventos',
    friSat: 'Vie & Sáb',
    night: 'Noche',
    storyPin: [
      { title: 'Masa Artesanal', body: 'Hecha diariamente — fermentada 48 horas para una corteza que lo dice todo.' },
      { title: 'Ingredientes Premium', body: 'Mariscos locales, quesos importados, tomate triturado a mano. Nada viene de lata.' },
      { title: 'Alma Caribeña', body: 'Nacido en Verón. Cada rebanada lleva la energía del barrio más auténtico de Punta Cana.' },
    ],
  },
  nav: {
    home: 'Inicio',
    menu: 'Menú',
    events: 'Noche',
    about: 'Nuestra Historia',
    gallery: 'Galería',
    order: 'Ordena',
    lang: 'EN',
  },
  hero: {
    kicker: 'En vivo desde Verón, Punta Cana',
    title1: 'Come.',
    title2: 'Bebe.',
    title3: 'Fiesta.',
    subtitle: 'Sabores tropicales urbanos de día. Energía nocturna de noche. Una sola dirección en Verón.',
    cta1: 'Ver Menú',
    cta2: 'Esta Noche',
    hours: '11:00 AM – Madrugada',
    location: 'Plaza Verón Center',
  },
  marquee: [
    'Come · Bebe · Fiesta',
    'Energía Tropical Urbana',
    'Verón, Punta Cana',
    'Pizza · Mariscos · Drinks',
  ],
  signature: {
    label: 'Selección Especial',
    title: 'Creado para despertar el antojo.',
    subtitle: 'Nuestros platos más pedidos — ingredientes premium, sabores intensos.',
    order: 'Pedir por WhatsApp',
    trending: 'Tendencia',
  },
  howItWorks: {
    label: 'Cómo Funciona',
    title: 'Ordena en 3 pasos.',
    steps: [
      { title: 'Elige tu Pedido', copy: 'Explora el menú y selecciona lo que quieres.' },
      { title: 'Escríbenos por WhatsApp', copy: 'Toca el botón y envía tu pedido directamente.' },
      { title: 'Relájate y Disfruta', copy: 'Lo preparamos fresco. Recoge o disfruta en el local.' },
    ],
  },
  dayNight: {
    day: {
      label: 'El Día',
      title: 'Familia. Sabores. Sol.',
      copy: 'Energía vibrante al mediodía, ambiente cálido y la mejor pizza de Verón.',
    },
    night: {
      label: 'La Noche',
      title: 'Beats. Botellas. Bajo.',
      copy: "DJs, noches de karaoke y ambiente inmersivo — D'Pavo es más que un restaurante.",
    },
  },
  reviews: {
    label: 'Lo Que Dicen',
    title: 'Amor real de clientes reales.',
  },
  hours: {
    label: 'Visítanos',
    title: 'Horario de Apertura.',
    address: 'HHXG+J29, 106, Punta Cana 23000',
    schedule: [
      { day: 'Lunes – Jueves', hours: '11:00 AM – 11:00 PM' },
      { day: 'Viernes', hours: '11:00 AM – 2:00 AM' },
      { day: 'Sábado', hours: '11:00 AM – 3:00 AM' },
      { day: 'Domingo', hours: '12:00 PM – 10:00 PM' },
    ],
    cta: 'Cómo Llegar por WhatsApp',
  },
  eventsCta: {
    label: 'Calendario Nocturno',
    title: 'Programación que se siente viva.',
    link: 'Ver Eventos',
  },
  cta: {
    label: 'No te Pierdas Nada',
    title: 'La fiesta nunca para.',
    subtitle: 'Ordena ahora, reserva una mesa o simplemente ven — siempre estamos encendidos.',
    cta1: 'Ver Menú',
    cta2: 'Reservar por WhatsApp',
  },
  footer: {
    tagline: 'Pizza, tragos y vida nocturna en Verón. Más fuerte, más intenso, más memorable.',
    explore: 'Explorar',
    visit: 'Visítanos',
    address: 'HHXG+J29, 106, Punta Cana 23000',
    hoursShort: '11:00 AM — Madrugada',
    whatsapp: 'Reservas por WhatsApp',
    rights: "D'Pavo Urban Pizzeria.",
  },
  menuPage: {
    label: 'Sabores de Alto Octanaje',
    title: 'El Menú.',
    subtitle: 'Pizzas, mariscos, picaderas y bebidas — todo disponible por WhatsApp.',
    categories: ['Todo', 'Pizza', 'Mariscos', 'Picaderas', 'Bebidas'],
    featured: 'Destacado',
    trending: 'Tendencia',
    order: 'Pedir por WhatsApp',
    ask: 'Consultar por WhatsApp',
  },
  eventsPage: {
    label: '¿Qué pasa esta noche?',
    title: 'Eventos y Vida Nocturna.',
    subtitle: 'DJs, karaoke y locura total cada semana en Verón.',
    featuredLabel: 'Evento Principal',
    reserve: 'Reservar Mesa',
    vibeLabel: 'El Ambiente',
    vibeTitle: 'Más que un restaurante.',
    vibes: [
      { title: 'Sets de DJ', copy: 'House, reggaetón y mezclas urbanas todos los viernes y sábados.' },
      { title: 'Música en Vivo', copy: 'Artistas locales y sorpresas a lo largo del mes.' },
      { title: 'Noches de Karaoke', copy: 'Todos los jueves — el público toma el micrófono.' },
    ],
    notifyLabel: 'Mantente Informado',
    notifyTitle: 'Recibe notificaciones de próximos eventos.',
    notifyCta: 'Únete por WhatsApp',
    weeklyLabel: 'Programación Semanal',
    weeklyTitle: 'Calendario Urbano.',
    reserveNow: 'Reservar Ahora',
  },
  aboutPage: {
    label: 'Nuestra Historia',
    title: 'Nuestra Historia.',
    venuePlaceholder: 'Foto del Local',
    subtitle: 'Un lugar nacido en Verón con ambición, sabor y ritmo.',
    storyTitle: "Cómo Empezó D'Pavo.",
    storyBody: [
      "D'Pavo nació de una idea simple: llevar pizza premium y de sabores intensos al corazón de Verón, Punta Cana — un barrio lleno de energía, cultura y gente hambrienta.",
      'Lo que comenzó como una pequeña operación de cocina rápidamente se convirtió en un destino urbano completo. La comida mejoró, las noches se pusieron más intensas y la marca tomó vida propia.',
      "Hoy D'Pavo es donde los locales comen, los turistas descubren y la vida nocturna comienza.",
    ],
    valuesLabel: 'En Qué Creemos',
    valuesTitle: 'Construido Sobre Tres Pilares.',
    values: [
      { title: 'Raíces Locales', copy: 'Nacidos y criados en Verón. Compramos local, pensamos local y devolvemos localmente.' },
      { title: 'Energía Urbana', copy: "De día o de noche, D'Pavo trae la energía — comida, música y ambiente." },
      { title: 'Ingredientes Premium', copy: 'Cada pizza, cada trago, cada plato está hecho con calidad que se nota.' },
    ],
    visitLabel: 'Ven a Vernos',
    visitTitle: 'Siempre Abiertos.',
    visitCta: 'Cómo Llegar',
  },
  galleryPage: {
    label: 'Galería',
    title: 'El Ambiente.',
    subtitle: "Comida, noches y la energía de D'Pavo — capturada.",
    categories: ['Todo', 'Comida', 'Local', 'Eventos'],
  },
};
